services:
  mysql:
    image: mysql:8.0
    container_name: casael_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: casael
      MYSQL_USER: casael
      MYSQL_PASSWORD: casael
    volumes:
      - casael_mysql_data:/var/lib/mysql

volumes:
  casael_mysql_data:
